# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(455, 546)
        font = QtGui.QFont()
        font.setItalic(False)
        font.setStrikeOut(False)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background - color: rgb(255, 250, 180)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_label = QtWidgets.QLabel(self.centralwidget)
        self.main_label.setGeometry(QtCore.QRect(40, 30, 371, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.main_label.setFont(font)
        self.main_label.setStyleSheet("color:rgb(170, 85, 0)")
        self.main_label.setObjectName("main_label")
        self.button_listen = QtWidgets.QPushButton(self.centralwidget)
        self.button_listen.setGeometry(QtCore.QRect(200, 100, 51, 51))
        self.button_listen.setObjectName("button_listen")
        self.picture = QtWidgets.QLabel(self.centralwidget)
        self.picture.setGeometry(QtCore.QRect(200, 100, 51, 51))
        self.picture.setText("")
        self.picture.setPixmap(QtGui.QPixmap("../microphone.jpg"))
        self.picture.setScaledContents(True)
        self.picture.setObjectName("picture")
        self.label_text = QtWidgets.QLabel(self.centralwidget)
        self.label_text.setGeometry(QtCore.QRect(30, 160, 401, 281))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_text.setFont(font)
        self.label_text.setStyleSheet("background_color:rgb(255, 255, 255);\n"
"color:rgb(170, 85, 0)")
        self.label_text.setText("")
        self.label_text.setObjectName("label_text")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 455, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Голосовий помічник"))
        self.main_label.setText(_translate("MainWindow", "Дай мені будь-яке завдання!"))
        self.button_listen.setText(_translate("MainWindow", "ф"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
