# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.new.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 611)
        font = QtGui.QFont()
        font.setPointSize(5)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color:rgb(255, 203, 250);\n"
"color: rgb(179, 0, 89);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-280, -30, 1301, 121))
        self.label.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        self.label_text2 = QtWidgets.QLabel(self.centralwidget)
        self.label_text2.setEnabled(True)
        self.label_text2.setGeometry(QtCore.QRect(-110, 60, 1091, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_text2.setFont(font)
        self.label_text2.setCursor(QtGui.QCursor(QtCore.Qt.SizeBDiagCursor))
        self.label_text2.setObjectName("label_text2")
        self.btn_micro = QtWidgets.QPushButton(self.centralwidget)
        self.btn_micro.setGeometry(QtCore.QRect(350, 470, 111, 81))
        self.btn_micro.setObjectName("btn_micro")
        self.photo_micro = QtWidgets.QLabel(self.centralwidget)
        self.photo_micro.setGeometry(QtCore.QRect(350, 460, 121, 91))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.photo_micro.setFont(font)
        self.photo_micro.setText("")
        self.photo_micro.setPixmap(QtGui.QPixmap("mikro.jpg"))
        self.photo_micro.setScaledContents(True)
        self.photo_micro.setObjectName("photo_micro")
        self.main_label = QtWidgets.QLabel(self.centralwidget)
        self.main_label.setGeometry(QtCore.QRect(30, 120, 751, 321))
        self.main_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.main_label.setText("")
        self.main_label.setObjectName("main_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Голосовий помічник"))
        self.label.setText(_translate("MainWindow", "                                       Твій голосовий помічник  Нуклеус"))
        self.label_text2.setText(_translate("MainWindow", "                                               Задай мені будь-яке питання                                                                                      т."))
        self.btn_micro.setText(_translate("MainWindow", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
